const safePayload = {
  "Flow Duration": 36483,
  "Total Fwd Packets": 2,
  "Total Backward Packets": 1,
  "Total Length of Fwd Packets": 0,
  "Total Length of Bwd Packets": 0,
  "Fwd Packet Length Max": 0,
  "Fwd Packet Length Min": 0,
  "Fwd Packet Length Mean": 0,
  "Fwd Packet Length Std": 0,
  "Bwd Packet Length Max": 0,
  "Bwd Packet Length Min": 0,
  "Bwd Packet Length Mean": 0,
  "Bwd Packet Length Std": 0,
  "Flow Bytes/s": 0,
  "Flow Packets/s": 82.23007976,
  "Flow IAT Mean": 18241.5,
  "Flow IAT Std": 25701.21018,
  "Flow IAT Max": 36415,
  "Flow IAT Min": 68,
  "Fwd IAT Total": 36483,
  "Fwd IAT Mean": 36483,
  "Fwd IAT Std": 0,
  "Fwd IAT Max": 36483,
  "Fwd IAT Min": 36483,
  "Bwd IAT Total": 0,
  "Bwd IAT Mean": 0,
  "Bwd IAT Std": 0,
  "Bwd IAT Max": 0,
  "Bwd IAT Min": 0,
  "Fwd PSH Flags": 0,
  "Bwd PSH Flags": 0,
  "Fwd URG Flags": 0,
  "Bwd URG Flags": 0,
  "Fwd Header Length": 60,
  "Bwd Header Length": 40,
  "Fwd Packets/s": 54.82005318,
  "Bwd Packets/s": 27.41002659,
  "Min Packet Length": 0,
  "Max Packet Length": 0,
  "Packet Length Mean": 0,
  "Packet Length Std": 0,
  "Packet Length Variance": 0,
  "FIN Flag Count": 0,
  "SYN Flag Count": 0,
  "RST Flag Count": 0,
  "PSH Flag Count": 1,
  "ACK Flag Count": 0,
  "URG Flag Count": 0,
  "CWE Flag Count": 0,
  "ECE Flag Count": 0,
  "Down/Up Ratio": 0,
  "Average Packet Size": 0,
  "Avg Fwd Segment Size": 0,
  "Avg Bwd Segment Size": 0,
  "Fwd Header Length.1": 60,
  "Fwd Avg Bytes/Bulk": 0,
  "Fwd Avg Packets/Bulk": 0,
  "Fwd Avg Bulk Rate": 0,
  "Bwd Avg Bytes/Bulk": 0,
  "Bwd Avg Packets/Bulk": 0,
  "Bwd Avg Bulk Rate": 0,
  "Subflow Fwd Packets": 2,
  "Subflow Fwd Bytes": 0,
  "Subflow Bwd Packets": 1,
  "Subflow Bwd Bytes": 0,
  "Init_Win_bytes_forward": 29200,
  "Init_Win_bytes_backward": 42408,
  "act_data_pkt_fwd": 0,
  "min_seg_size_forward": 20,
  "Active Mean": 0,
  "Active Std": 0,
  "Active Max": 0,
  "Active Min": 0,
  "Idle Mean": 0,
  "Idle Std": 0,
  "Idle Max": 0,
  "Idle Min": 0
};

function createPayload(overrides) {
  return {
    ...safePayload,
    ...overrides
  };
}

const dosPayload = createPayload({
  "Flow Duration": 18319742,
  "Total Fwd Packets": 1,
  "Total Backward Packets": 1,
  "Total Length of Fwd Packets": 187,
  "Fwd Packet Length Max": 187,
  "Fwd Packet Length Min": 187,
  "Fwd Packet Length Mean": 187,
  "Flow Bytes/s": 10.20756733,
  "Flow Packets/s": 0.109171843,
  "Flow IAT Mean": 18300000,
  "Flow IAT Std": 0,
  "Flow IAT Max": 18300000,
  "Flow IAT Min": 18300000,
  "Fwd IAT Total": 0,
  "Fwd IAT Mean": 0,
  "Fwd IAT Max": 0,
  "Fwd IAT Min": 0,
  "Fwd PSH Flags": 1,
  "Fwd Header Length": 32,
  "Fwd Packets/s": 0.054585922,
  "Bwd Packets/s": 0.054585922,
  "Max Packet Length": 187,
  "Packet Length Mean": 124.6666667,
  "Packet Length Std": 107.9645003,
  "Packet Length Variance": 11656.33333,
  "SYN Flag Count": 1,
  "PSH Flag Count": 0,
  "ACK Flag Count": 1,
  "URG Flag Count": 1,
  "Down/Up Ratio": 1,
  "Average Packet Size": 187,
  "Avg Fwd Segment Size": 187,
  "Fwd Header Length.1": 32,
  "Subflow Fwd Packets": 1,
  "Subflow Fwd Bytes": 187,
  "Init_Win_bytes_forward": 229,
  "Init_Win_bytes_backward": 28960,
  "min_seg_size_forward": 32,
  "Idle Mean": 18300000,
  "Idle Max": 18300000,
  "Idle Min": 18300000
});

const bruteForcePayload = createPayload({
  "Flow Duration": 1,
  "Total Fwd Packets": 1,
  "Total Backward Packets": 1,
  "Total Length of Fwd Packets": 14,
  "Fwd Packet Length Max": 14,
  "Fwd Packet Length Min": 14,
  "Fwd Packet Length Mean": 14,
  "Flow Bytes/s": 14000000,
  "Flow Packets/s": 2000000,
  "Flow IAT Mean": 1,
  "Flow IAT Std": 0,
  "Flow IAT Max": 1,
  "Flow IAT Min": 1,
  "Fwd IAT Total": 0,
  "Fwd IAT Mean": 0,
  "Fwd IAT Max": 0,
  "Fwd IAT Min": 0,
  "Fwd PSH Flags": 1,
  "Fwd Header Length": 32,
  "Bwd Header Length": 32,
  "Fwd Packets/s": 1000000,
  "Bwd Packets/s": 1000000,
  "Max Packet Length": 14,
  "Packet Length Mean": 9.333333333,
  "Packet Length Std": 8.082903769,
  "Packet Length Variance": 65.33333333,
  "SYN Flag Count": 1,
  "PSH Flag Count": 0,
  "ACK Flag Count": 1,
  "Down/Up Ratio": 1,
  "Average Packet Size": 14,
  "Avg Fwd Segment Size": 14,
  "Fwd Header Length.1": 32,
  "Subflow Fwd Packets": 1,
  "Subflow Fwd Bytes": 14,
  "Init_Win_bytes_forward": 227,
  "Init_Win_bytes_backward": 227,
  "min_seg_size_forward": 32
});

const portScanPayload = createPayload({
  "Flow Duration": 11010851,
  "Total Fwd Packets": 4,
  "Total Backward Packets": 2,
  "Total Length of Fwd Packets": 18,
  "Fwd Packet Length Max": 18,
  "Fwd Packet Length Mean": 4.5,
  "Fwd Packet Length Std": 9,
  "Flow Bytes/s": 1.634751029,
  "Flow Packets/s": 0.54491701,
  "Flow IAT Mean": 2202170.2,
  "Flow IAT Std": 3035893.654,
  "Flow IAT Max": 6006342,
  "Flow IAT Min": 104,
  "Fwd IAT Total": 11000000,
  "Fwd IAT Mean": 3670283.667,
  "Fwd IAT Std": 3217343.118,
  "Fwd IAT Max": 6006342,
  "Fwd IAT Min": 571,
  "Bwd IAT Total": 6006926,
  "Bwd IAT Mean": 6006926,
  "Bwd IAT Max": 6006926,
  "Bwd IAT Min": 6006926,
  "Fwd Header Length": 136,
  "Bwd Header Length": 72,
  "Fwd Packets/s": 0.363278006,
  "Bwd Packets/s": 0.181639003,
  "Max Packet Length": 18,
  "Packet Length Mean": 2.571428571,
  "Packet Length Std": 6.803360514,
  "Packet Length Variance": 46.28571429,
  "Average Packet Size": 3,
  "Avg Fwd Segment Size": 4.5,
  "Fwd Header Length.1": 136,
  "Subflow Fwd Packets": 4,
  "Subflow Fwd Bytes": 18,
  "Subflow Bwd Packets": 2,
  "Init_Win_bytes_forward": 29200,
  "Init_Win_bytes_backward": 227,
  "act_data_pkt_fwd": 1,
  "min_seg_size_forward": 32,
  "Active Mean": 571,
  "Active Max": 571,
  "Active Min": 571,
  "Idle Mean": 6006342,
  "Idle Max": 6006342,
  "Idle Min": 6006342
});

export const examplePayloads = [
  {
    id: "safe",
    label: "Safe",
    badge: "Predicts 0",
    description: "Model-confirmed benign traffic sample from the CICIDS-style feature set.",
    expectedPrediction: "0",
    payload: safePayload
  },
  {
    id: "unsafe",
    label: "Unsafe",
    badge: "Predicts 1",
    description: "General malicious preset using a high-rate BruteForce row that the model classifies as attack.",
    expectedPrediction: "1",
    payload: bruteForcePayload
  },
  {
    id: "dos",
    label: "DoS",
    badge: "Predicts 1",
    description: "Denial-of-service sample with the model's strongest attack confidence in the available data.",
    expectedPrediction: "1",
    payload: dosPayload
  },
  {
    id: "bruteforce",
    label: "Brute Force",
    badge: "Predicts 1",
    description: "Authentication-style burst sample with extremely high flow and packet rates.",
    expectedPrediction: "1",
    payload: bruteForcePayload
  },
  {
    id: "portscan",
    label: "Port Scan",
    badge: "Predicts 1",
    description: "Reconnaissance-like traffic sample with sparse payload bytes and long idle timing.",
    expectedPrediction: "1",
    payload: portScanPayload
  }
];

export function stringifyPayload(payload) {
  return JSON.stringify(payload, null, 2);
}
